### ISSUE TITLE
issue resolved

### ISSUE THREAD

**Issue by quattrinia** [matthewhvandam/integrating-functional-genomics-into-phylogenomics#1]
Hi there,

I am excited to use this new  pipeline that you created. It looks super useful!  Quick question for you. Results from this:

for (i in 1:nrow(gff_mods)){ 

	if(gff_mods[i,3 ]=="gene"){
		curgeneid = gff_mods[i,9 ]
	}
	gff_mods[i, 12]= curgeneid 
	print(row.names(gff_mods[i,]))	
}

are currently printing to screen. Does it feed into the next command? Should it be defined?
Thanks!
Andrea

**Comment by quattrinia** [comment]
This seemed to work ok! And, didn't take too long to run

**Comment by matthewhvandam** [comment]
You should be using
https://github.com/calacademy-research/ccgutils/tree/master/uce_types

to do the basic UCE annotation. It does all the things the R codes does in
a few different commands. It will give you tables that you can easily use
to concatenate the UCE sets together using basic subsetting. The R code is
more of an archive.

**Comment by quattrinia** [comment]
Ok cool. thanks! I did run into other issues, so I will try this~
Cheers.
